name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  RUNID: ${{ github.run_number }}
  TAG: ${{ github.ref_name }}
  MELOS_VERSION: 6.0.0

jobs:
  docker-deploy:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
 
      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
 
      - name: Melos action
        uses: bluefireteam/melos-action@v3
        with:
          melos-version: ${{ env.MELOS_VERSION }}
          run-bootstrap: true

      - run: melos publish --dry-run

 